/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 4;
=======
const int buildversion = 13;
>>>>>>> 3a0d750bde810688dcbc7c5bb15e45abc6a90c2c
const char buildconfig[] = "ASST2";
