/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 203;
=======
const int buildversion = 158;
>>>>>>> a67605f807176f494e9b12198589510f9a3bcc71
const char buildconfig[] = "ASST2";
