/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 89;
=======
const int buildversion = 17;
>>>>>>> fe6731948c644cd77532489b42f507fa0a5d3e4b
const char buildconfig[] = "ASST2";
